### PR TITLE
test prow

### PR DESCRIPTION
**Pull request by xcliu-ca**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
```

### CODE REVIEW

**Review by xcliu-ca — COMMENTED** [review]
/lgtm

**Comment by lospringliu** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/xcliu-ca-ibm/ibm-healthcheck-operator/pull/1#" title="Author self-approved">xcliu-ca</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](?repo=xcliu-ca-ibm%2Fibm-healthcheck-operator).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/xcliu-ca-ibm/ibm-healthcheck-operator/blob/release-ltsr/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by lospringliu** [comment]
@xcliu-ca: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
check-ibm-healthcheck-operator | 3d442562fe5c62f968f8d0ecb56b614682762c25 | [link](http://prow2.purple-chesterfield.com/log?job=check-ibm-healthcheck-operator&id=1646271886486671361) | `/test check-ibm-healthcheck-operator`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by lospringliu — APPROVED** [review]
/lgtm

**Comment by lospringliu** [comment]
New changes are detected. LGTM label has been removed.

**Review by lospringliu — APPROVED** [review]
/lgtm

**Pull request merged**
